# Generated by Django 5.2.9 on 2026-08-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to=settings.AUTH_USER_MODEL)),
                ('default_target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_glossaries', to='core.language')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_glossaries', to='core.language')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossaries', to='core.subject')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=240)),
                ('definition', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=80)),
                ('pronunciation_url', models.URLField(blank=True)),
                ('is_exam_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='glossary.glossary')),
            ],
            options={
                'ordering': ('phrase',),
            },
        ),
        migrations.CreateModel(
            name='TermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('example', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_translations', to='core.language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='glossary.term')),
            ],
            options={
                'ordering': ('language__name',),
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('glossary', 'phrase'), name='unique_glossary_phrase'),
        ),
        migrations.AddConstraint(
            model_name='termtranslation',
            constraint=models.UniqueConstraint(fields=('term', 'language'), name='unique_term_language'),
        ),
    ]
