#!/usr/bin/env python3
"""Validate local links and generated-file ownership in Markdown documents."""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent.parent
LINK = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
GENERATED_MARKER = "<!-- Generated by scripts/generate_documentation.py; do not edit. -->"


def markdown_files() -> list[Path]:
    files = list(ROOT.glob("*.md"))
    files.extend((ROOT / "docs").rglob("*.md"))
    return sorted(files)


def main() -> int:
    failures: list[str] = []
    generated = ROOT / "docs" / "generated"
    for path in markdown_files():
        content = path.read_text(encoding="utf-8")
        if generated in path.parents and not content.startswith(GENERATED_MARKER):
            failures.append(f"{path.relative_to(ROOT)}: generated file lacks ownership marker")
        for match in LINK.finditer(content):
            target = match.group(1).strip().split(maxsplit=1)[0].strip('<>"')
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target_path = unquote(target.split("#", 1)[0])
            resolved = (path.parent / target_path).resolve()
            try:
                resolved.relative_to(ROOT.resolve())
            except ValueError:
                failures.append(f"{path.relative_to(ROOT)}: link escapes repository: {target}")
                continue
            if not resolved.exists():
                failures.append(f"{path.relative_to(ROOT)}: missing link target: {target}")

    if failures:
        print("Documentation validation failed:")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    print(f"Documentation links and ownership markers are valid ({len(markdown_files())} files).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
